name: Build
on:
  push:
jobs:
  build-linux:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure Project
        run: |
          chmod +x ./setup.sh
          ./setup.sh

      - name: Build Project
        run: |
          cmake --build build --config Release

  build-windows:
    name: Build Project
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install Packages
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.sh
          vcpkg integrate install
          cd ..

      - name: Configure and Build Project
        run: |
          cmake -S . -B ./build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -Wno-dev
          cmake --build build --config Release

      - name: Generate Installer
        run: |
          choco install innosetup
          C:/"Program Files (x86)"/"Inno Setup 6"/ISCC.exe windowsiss.iss

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: D:\a\wpical\wpical\Output\mysetup.exe
          name: WPIcal
