name: Build
on:
  push:
jobs:
  build-linux:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run setup.sh
        run: |
          chmod +x ./setup.sh
          ./setup.sh

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: .
          build-dir: ./build
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++


  build-windows:
      name: Build Project
      runs-on: windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7

        - name: Install Packages
          run: |
            git clone https://github.com/microsoft/vcpkg.git
            cd vcpkg
            bootstrap-vcpkg.sh
            vcpkg integrate install
            vcpkg install
            cd ..

        - name: Configure and Build Project
          uses: threeal/cmake-action@main
          with:
            source-dir: .
            build-dir: ./build
            generator: Visual Studio 17 2022
            c-compiler: msvc
            cxx-compiler: msvc
    